# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/blackseadigital/partners/models/category/fields.yaml

# Model Class name
modelClass: BlackSeaDigital\Partners\Models\Category

# Default redirect location
defaultRedirect: blackseadigital/partners/categories

# Create page
create:
    title: backend::lang.form.create_title
    redirect: blackseadigital/partners/categories/update/:id
    redirectClose: blackseadigital/partners/categories

# Update page
update:
    title: backend::lang.form.update_title
    redirect: blackseadigital/partners/categories
    redirectClose: blackseadigital/partners/categories

# Preview page
preview:
    title: backend::lang.form.preview_title
