# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Partner

# Model Form Field configuration
form: $/blackseadigital/partners/models/partner/fields.yaml

# Model Class name
modelClass: BlackSeaDigital\Partners\Models\Partner

# Default redirect location
defaultRedirect: blackseadigital/partners/partners

# Create page
create:
    title: backend::lang.form.create_title
    redirect: blackseadigital/partners/partners/update/:id
    redirectClose: blackseadigital/partners/partners

# Update page
update:
    title: backend::lang.form.update_title
    redirect: blackseadigital/partners/partners
    redirectClose: blackseadigital/partners/partners

# Preview page
preview:
    title: backend::lang.form.preview_title
