# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: City

# Model Form Field configuration
form: $/blackseadigital/partners/models/city/fields.yaml

# Model Class name
modelClass: BlackSeaDigital\Partners\Models\City

# Default redirect location
defaultRedirect: blackseadigital/partners/cities

# Create page
create:
    title: backend::lang.form.create_title
    redirect: blackseadigital/partners/cities/update/:id
    redirectClose: blackseadigital/partners/cities

# Update page
update:
    title: backend::lang.form.update_title
    redirect: blackseadigital/partners/cities
    redirectClose: blackseadigital/partners/cities

# Preview page
preview:
    title: backend::lang.form.preview_title
